steps:
  # Docker build
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/${PROJECT_ID}/csci-5709-kubernetes-repo/container2:latest",
        ".",
      ]

  # Docker Push
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/${PROJECT_ID}/csci-5709-kubernetes-repo/container2:latest",
      ]

  # Deploy to GKE for Container 1
  - name: "gcr.io/cloud-builders/kubectl"
    args: ["apply", "-f", "deployment.yaml"]
    env:
      - "CLOUDSDK_COMPUTE_ZONE=us-central1"
      - "CLOUDSDK_CONTAINER_CLUSTER=hatim-cluster"
      - "CLOUDSDK_CORE_PROJECT=${PROJECT_ID}"

images:
  - "us-central1-docker.pkg.dev/${PROJECT_ID}/csci-5709-kubernetes-repo/container2:latest"
