apiVersion: apps/v1
kind: Deployment
metadata:
  name: container2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container2
  template:
    metadata:
      labels:
        app: container2
    spec:
      containers:
        - name: container2
          image: us-central1-docker.pkg.dev/braided-visitor-417017/csci-5709-kubernetes-repo/container2:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5002
          volumeMounts:
            - name: shared-volume
              mountPath: /hatim_PV_dir
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: shared-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: container2-service
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 81
      targetPort: 5002
  selector:
    app: container2
